name: Push to DockerHub and Run it on the Remote Server

on:
    push:
        branches:
            - master
        tags:
            - v*
    pull_request:
        branches:
            - master

env:
    IMAGE_NAME: tampermokey-script-dev
    REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    REMOTE_USER: ${{ secrets.REMOTE_USER }}
    REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log into Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker image
              run: docker build -t ${{ env.IMAGE_NAME }} .

            - name: Push Docker image
              run: |
                  IMAGE_ID=${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

                  # Ensure the image ID is in lowercase
                  IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')

                  # Determine version tag
                  VERSION=${{ github.sha }}
                  if [[ "${{ github.ref }}" == refs/tags/* ]]; then
                    VERSION=${{ github.ref }}
                    VERSION=${VERSION##*/}  # Get the tag name from the ref
                  elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
                    VERSION=latest
                  fi

                  # Trim version to 7 characters for non-tagged commits
                  if [[ "$VERSION" != "latest" ]]; then
                    VERSION=${VERSION:0:7}
                  fi

                  # Tag and push the image
                  docker tag ${{ env.IMAGE_NAME }} $IMAGE_ID:$VERSION
                  docker push $IMAGE_ID:$VERSION

                  # Optionally push the latest tag if on main branch
                  if [[ "$VERSION" != "latest" && "${{ github.ref }}" == refs/heads/main ]]; then
                    docker tag ${{ env.IMAGE_NAME }} $IMAGE_ID:latest
                    docker push $IMAGE_ID:latest

            - name: Deploy to Remote Server
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{ env.REMOTE_HOST }}
                  username: ${{ env.REMOTE_USER }}
                  key: ${{ env.REMOTE_SSH_KEY }}
                  script: |
                      IMAGE_ID=${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
                      VERSION=${{ github.sha }}
                      if [[ "${{ github.ref }}" == refs/tags/* ]]; then
                        VERSION=${{ github.ref }}
                        VERSION=${VERSION##*/}  # Get the tag name from the ref
                      elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
                        VERSION=latest
                      fi

                      if [[ "$VERSION" != "latest" ]]; then
                        VERSION=${VERSION:0:7}
                      fi

                      docker pull $IMAGE_ID:$VERSION
                      docker stop my_app_container || true
                      docker rm my_app_container || true
                      docker run -d --name my_app_container -p 80:80 $IMAGE_ID:$VERSION
